if(NOT DEFINED LCNC_SOURCE_ROOT OR NOT DEFINED LCNC_TEST_BINARY_ROOT)
    message(FATAL_ERROR "Host 边界测试必须提供源码与独立证据目录")
endif()
file(READ "${LCNC_SOURCE_ROOT}/include/lasercnc/kernel/app_kernel.hpp" original)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(evidence "${LCNC_TEST_BINARY_ROOT}/host-state-${suffix}")
foreach(mode IN ITEMS healthy history persistence)
    set(header "${original}")
    if(mode STREQUAL "history")
        string(REPLACE "const runtime::HistoryRuntime& history() const noexcept"
            "runtime::HistoryRuntime& history() noexcept" header "${header}")
    elseif(mode STREQUAL "persistence")
        string(REPLACE "const persistence::PersistenceService& persistence() const noexcept"
            "persistence::PersistenceService& persistence() noexcept" header "${header}")
    endif()
    if(NOT mode STREQUAL "healthy" AND header STREQUAL original)
        message(FATAL_ERROR "Host 边界负例未能修改预期声明：${mode}")
    endif()
    set(root "${evidence}/${mode}")
    file(MAKE_DIRECTORY "${root}/include/lasercnc/kernel")
    file(WRITE "${root}/include/lasercnc/kernel/app_kernel.hpp" "${header}")
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DLCNC_SOURCE_ROOT=${root}"
        -P "${LCNC_SOURCE_ROOT}/cmake/VerifyKernelBoundaries.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    file(WRITE "${root}/result.log" "exit=${result}\n${output}\n${error}")
    if(mode STREQUAL "healthy")
        if(NOT result STREQUAL "0")
            message(FATAL_ERROR "健康 Host 头文件未通过：${evidence}")
        endif()
    elseif(NOT result MATCHES "^[1-9][0-9]*$" OR NOT error MATCHES "可绕过模块治理或执行网关")
        message(FATAL_ERROR "Host 边界扫描未按预期拒绝 ${mode}：${evidence}")
    endif()
endforeach()
message(STATUS "Host 状态边界健康对照及两个负例通过；证据：${evidence}")
