cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED PROBE OR NOT DEFINED EVIDENCE_ROOT)
    message(FATAL_ERROR "缺少目录 epoch 探针或证据目录")
endif()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef run_id)
set(run_root "${EVIDENCE_ROOT}/${run_id}")
file(MAKE_DIRECTORY "${run_root}")
set(project_epochs)
set(document_epochs)
foreach(step RANGE 0 2)
    if(step EQUAL 0)
        set(mode seed)
    else()
        set(mode read)
    endif()
    execute_process(COMMAND "${PROBE}" "${run_root}" "${mode}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
    file(WRITE "${run_root}/process-${step}.log" "exit=${result}\n${output}\n${errors}")
    if(NOT "${result}" STREQUAL "0" OR NOT output MATCHES "closed-detached-no-execution")
        message(FATAL_ERROR "目录 epoch 进程 ${step} 失败，材料保留：${run_root}")
    endif()
    foreach(kind IN ITEMS project document)
        string(REGEX MATCH "${kind}=([0-9a-f]+)" matched "${output}")
        set(epoch "${CMAKE_MATCH_1}")
        string(LENGTH "${epoch}" epoch_length)
        if(NOT epoch_length EQUAL 32 OR epoch STREQUAL "00000000000000000000000000000000")
            message(FATAL_ERROR "目录 ${kind} epoch 格式无效：${run_root}")
        endif()
        if(epoch IN_LIST project_epochs OR epoch IN_LIST document_epochs)
            message(FATAL_ERROR "跨 Runtime/进程复用了目录 epoch：${run_root}")
        endif()
        list(APPEND ${kind}_epochs "${epoch}")
    endforeach()
endforeach()
message(STATUS "lifecycle-catalog-three-process-verified: ${run_root}")
