if(NOT EXISTS "${SOURCE_ROOT}/cmake/RunVerifiedProgram.cmake" OR NOT DEFINED EVIDENCE_ROOT)
    message(FATAL_ERROR "Verified program source and evidence root are required")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(root "${EVIDENCE_ROOT}/${suffix}")
file(MAKE_DIRECTORY "${root}")
foreach(mode IN ITEMS healthy marker-then-failure missing-marker sanitizer-report)
    set(fixture "${root}/${mode}.cmake")
    if(mode STREQUAL "missing-marker")
        file(WRITE "${fixture}" "message(STATUS \"not-the-success-token\")\n")
        set(expected "VerifiedProgram.MissingMarker")
    else()
        file(WRITE "${fixture}" "message(STATUS \"verified-program-success\")\n")
        if(mode STREQUAL "marker-then-failure")
            file(APPEND "${fixture}" "message(FATAL_ERROR \"intentional late failure\")\n")
            set(expected "VerifiedProgram.NonzeroExit")
        elseif(mode STREQUAL "sanitizer-report")
            file(APPEND "${fixture}" "message(\"ERROR: AddressSanitizer: synthetic-regression-probe\")\n")
            set(expected "VerifiedProgram.SanitizerReport")
        endif()
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DLCNC_EXECUTABLE=${CMAKE_COMMAND}"
        "-DLCNC_ARGUMENTS=-P;${fixture}" "-DLCNC_EXPECTED_OUTPUT=verified-program-success"
        -P "${SOURCE_ROOT}/cmake/RunVerifiedProgram.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    file(WRITE "${root}/${mode}.log" "exit=${result}\n${output}\n${error}")
    if(mode STREQUAL "healthy")
        if(NOT result STREQUAL "0" OR NOT output MATCHES "verified-program-success")
            message(FATAL_ERROR "Healthy verified program was rejected: ${root}")
        endif()
    elseif(NOT result MATCHES "^[1-9][0-9]*$" OR NOT error MATCHES "${expected}")
        message(FATAL_ERROR "Verified program guard missed ${mode}: ${root}")
    endif()
endforeach()
message(STATUS "Verified program exit/marker guards passed; evidence: ${root}")
