cmake_minimum_required(VERSION 3.24)
if(NOT DEFINED PROBE OR NOT DEFINED EVIDENCE_ROOT)
    message(FATAL_ERROR "缺少快照身份探针或证据目录")
endif()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef run_id)
set(run_root "${EVIDENCE_ROOT}/${run_id}")
file(MAKE_DIRECTORY "${run_root}")
set(all_keys)
foreach(step RANGE 0 2)
    execute_process(COMMAND "${PROBE}" "${run_root}" "${step}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 60)
    file(WRITE "${run_root}/process-${step}.log" "exit=${result}\n${output}\n${errors}")
    if(NOT "${result}" STREQUAL "0" OR NOT output MATCHES "close-snapshot-process-verified")
        message(FATAL_ERROR "快照身份进程 ${step} 失败，材料保留：${run_root}")
    endif()
    string(REGEX MATCHALL "new=snapshot[.]close[.]v2[.][0-9a-f]+" entries "${output}")
    list(LENGTH entries count)
    if(NOT count EQUAL 8)
        message(FATAL_ERROR "进程 ${step} 未生成完整的八个新快照：${run_root}")
    endif()
    foreach(entry IN LISTS entries)
        string(LENGTH "${entry}" length)
        if(NOT length EQUAL 86 OR entry IN_LIST all_keys)
            message(FATAL_ERROR "快照身份格式错误或跨进程重用：${run_root}")
        endif()
        list(APPEND all_keys "${entry}")
    endforeach()
endforeach()
list(LENGTH all_keys total)
if(NOT total EQUAL 24)
    message(FATAL_ERROR "三进程证据不完整：${run_root}")
endif()
message(STATUS "close-snapshot-three-process-verified: ${run_root}")
