cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED LCNC_EXECUTABLE OR NOT EXISTS "${LCNC_EXECUTABLE}"
   OR NOT DEFINED LCNC_EXPECTED_OUTPUT)
    message(FATAL_ERROR "VerifiedProgram.InvalidArguments: program and success marker required")
endif()
if(NOT DEFINED LCNC_TIMEOUT)
    set(LCNC_TIMEOUT 30)
endif()
execute_process(COMMAND "${LCNC_EXECUTABLE}" ${LCNC_ARGUMENTS}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT "${LCNC_TIMEOUT}")
if(NOT result STREQUAL "0")
    message(FATAL_ERROR "VerifiedProgram.NonzeroExit: ${result}\n${output}\n${error}")
endif()
if("${output}\n${error}" MATCHES "(ERROR|SUMMARY): AddressSanitizer")
    message(FATAL_ERROR "VerifiedProgram.SanitizerReport: ${output}\n${error}")
endif()
if(NOT output MATCHES "${LCNC_EXPECTED_OUTPUT}")
    message(FATAL_ERROR "VerifiedProgram.MissingMarker: ${output}\n${error}")
endif()
message(STATUS "${output}")
if(NOT error STREQUAL "")
    message(STATUS "${error}")
endif()
